backend/Controllers/AtendimentoContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using site.Models;

namespace site.Controllers
{
    public class AtendimentoContatoController : Controller
    {
        private readonly Context _context;

        public AtendimentoContatoController(Context context)
        {
            _context = context;
        }

        // GET: AtendimentoContatoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Atendimento.ToListAsync());
        }

        // GET: AtendimentoContatoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendimentoContato = await _context.Atendimento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (atendimentoContato == null)
            {
                return NotFound();
            }

            return View(atendimentoContato);
        }

        // GET: AtendimentoContatoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AtendimentoContatoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Email,Mensagem")] AtendimentoContato atendimentoContato)
        {
            if (ModelState.IsValid)
            {
                _context.Add(atendimentoContato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(atendimentoContato);
        }

        // GET: AtendimentoContatoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendimentoContato = await _context.Atendimento.FindAsync(id);
            if (atendimentoContato == null)
            {
                return NotFound();
            }
            return View(atendimentoContato);
        }

        // POST: AtendimentoContatoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Email,Mensagem")] AtendimentoContato atendimentoContato)
        {
            if (id != atendimentoContato.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(atendimentoContato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AtendimentoContatoExists(atendimentoContato.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(atendimentoContato);
        }

        // GET: AtendimentoContatoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendimentoContato = await _context.Atendimento
                .FirstOrDefaultAsync(m => m.ID == id);
            if (atendimentoContato == null)
            {
                return NotFound();
            }

            return View(atendimentoContato);
        }

        // POST: AtendimentoContatoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atendimentoContato = await _context.Atendimento.FindAsync(id);
            _context.Atendimento.Remove(atendimentoContato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AtendimentoContatoExists(int id)
        {
            return _context.Atendimento.Any(e => e.ID == id);
        }
    }
}

backend/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using site.Models;

namespace site.Controllers
{
    public class PessoasController : Controller
    {
        private readonly Context _context;

        public PessoasController(Context context)
        {
            _context = context;
        }

        // GET: Pessoas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pessoas.ToListAsync());
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pessoas == null)
            {
                return NotFound();
            }

            return View(pessoas);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Origem,Destino,Saída,Retorno,Preço")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pessoas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoas);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas.FindAsync(id);
            if (pessoas == null)
            {
                return NotFound();
            }
            return View(pessoas);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Origem,Destino,Saída,Retorno,Preço")] Pessoas pessoas)
        {
            if (id != pessoas.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoasExists(pessoas.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoas);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pessoas == null)
            {
                return NotFound();
            }

            return View(pessoas);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoas = await _context.Pessoas.FindAsync(id);
            _context.Pessoas.Remove(pessoas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoasExists(int id)
        {
            return _context.Pessoas.Any(e => e.ID == id);
        }
    }
}

backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="icon" href="https://img.icons8.com/external-vitaliy-gorbachev-lineal-vitaly-gorbachev/60/ffffff/external-airplane-airport-vitaliy-gorbachev-lineal-vitaly-gorbachev-2.png" />
</head>
<body>
        <header>
            <nav class="navbar navBar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">

                <img src="https://img.icons8.com/external-vitaliy-gorbachev-fill-vitaly-gorbachev/60/000000/external-airplane-airport-vitaliy-gorbachev-fill-vitaly-gorbachev-2.png" alt="" width="50" class="logo" />

                <div class="container">

                    <a class="navbar-brand navA" asp-area="" asp-controller="" asp-action=""></a> <!--Recogency-->

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                        <ul class="navbar-nav flex-grow-1 navUl">

                            <li class="nav-item">
                                <a class="nav-link text-dark nav-Item" asp-area="Index" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark nav-Item" asp-area="" asp-controller="Home" asp-action="Destinos">Destinos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark nav-Item" asp-area="" asp-controller="Home" asp-action="Promocoes">Promoções</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark nav-Item" asp-area="" asp-controller="AtendimentoContato" asp-action="Create">Contato</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark nav-Item" asp-area="" asp-controller="Pessoas" asp-action="Create">Cadastro</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" >
            &copy; 2021 - <a class="botao" asp-area="" asp-controller="" asp-action="">Recogency</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>